### PR TITLE
Adds methods to force account refreshes

### PR DESCRIPTION
**Pull request by hammem**
Addresses request in #43 to request a refresh of accounts by Monarch.  Includes a convenience method to both make the request and poll to check if the request is completed.

### CODE REVIEW

**Comment by hammem** [comment]
@CalvinChanCan , please take a look and see if this is what you had in mind

**Comment by lzilioli** [comment]
Looks good to me! I have not had a chance to check out this branch and run it but code changes look good from my side. Will the caller need to pass the account ids as a parameter or do you generate that list yourself?

**Comment by hammem** [comment]
I was able to test all locally and it was working. 

As of now, you have to get the accounts and pass them in. 

I can update the convenience method to do the account list fetch as well, if not provided.

**Comment by lzilioli** [comment]
I believe that would be helpful. Would save me a line of code for my use case (since I want to refresh everything THEN fetch my accounts).

Thank you very much! Much appreciated.

**Comment by hammem** [comment]
@lzilioli , thanks for the feedback.  Updated the PR to make the `account_ids` param in the convenience method optional.

**Comment by lzilioli** [comment]
Just tried it and it works great for me! Thanks. @hammem

**Comment by CalvinChanCan** [comment]
Thanks @hammem! That works perfectly well for me too!

**Pull request merged**
